spring:
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
  datasource:
    url: jdbc:postgresql://localhost:5432/springSecurityTraining
    username: root
    password: 123
  flyway:
    baseline-on-migrate: true
server:
  port: 8580
logging:
  level:
    org:
      flywaydb: DEBUG
